# Generated by Django 2.2.4 on 2019-09-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='cust_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='desc',
            new_name='suggestion',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='date',
        ),
        migrations.AddField(
            model_name='customers',
            name='email',
            field=models.EmailField(default='abc@abc.com', max_length=254),
        ),
        migrations.AddField(
            model_name='customers',
            name='rating',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='customers',
            name='time_taken',
            field=models.IntegerField(default=-1),
        ),
    ]
