# Generated by Django 2.2.4 on 2019-09-01 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackapp', '0002_auto_20190901_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='time_taken',
            field=models.CharField(max_length=50),
        ),
    ]
